import { useState } from 'react'
import PublicLayout from '@/components/layout/PublicLayout'
import { Copy, Check } from 'lucide-react'

export default function DocumentationPage() {
  const [copied, setCopied] = useState<string | null>(null)

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text)
    setCopied(id)
    setTimeout(() => setCopied(null), 2000)
  }

  const sections = [
    {
      id: 'overview',
      title: 'Overview',
    },
    {
      id: 'why-requestvault',
      title: 'Why RequestVault Exists',
    },
    {
      id: 'core-capabilities',
      title: 'Core Capabilities',
    },
    {
      id: 'getting-started',
      title: 'Getting Started',
    },
    {
      id: 'how-it-works',
      title: 'How It Works',
    },
    {
      id: 'sdk-configuration',
      title: 'SDK Configuration',
    },
    {
      id: 'dashboard-analytics',
      title: 'Dashboard Analytics',
    },
    {
      id: 'security-and-privacy',
      title: 'Security and Privacy',
    },
    {
      id: 'production-recommendations',
      title: 'Production Recommendations',
    },
    {
      id: 'troubleshooting',
      title: 'Troubleshooting',
    },
  ]

  return (
    <PublicLayout>
      <div className="min-h-screen pt-20 pb-20">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid lg:grid-cols-4 gap-12">
            {/* Sidebar */}
            <aside className="lg:col-span-1 space-y-2">
              <div className="sticky top-24">
                <h3 className="text-sm font-semibold text-vault-text mb-4">Documentation</h3>
                {sections.map((section) => (
                  <a
                    key={section.id}
                    href={`#${section.id}`}
                    className="block px-4 py-2 rounded-lg text-sm text-vault-text-secondary hover:text-vault-text hover:bg-vault-border/30 transition-colors"
                  >
                    {section.title}
                  </a>
                ))}
              </div>
            </aside>

            {/* Main content */}
            <main className="lg:col-span-3 space-y-16">
              {/* Overview */}
              <section id="overview" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Overview</h2>
                <div className="space-y-6 text-vault-text-secondary">
                  <p>
                    Modern applications depend on APIs. Every payment gateway, authentication provider, AI service, 
                    analytics platform, notification system, and internal microservice introduces another network 
                    dependency that can fail, slow down, or behave unexpectedly.
                  </p>
                  <p>
                    When something goes wrong, developers are often left piecing together information from scattered 
                    logs, exception traces, monitoring tools, and third-party dashboards.
                  </p>
                  <p>
                    RequestVault was built to solve that problem. RequestVault provides a single place to observe, 
                    inspect, and analyze outbound API traffic generated by your application. By integrating a 
                    lightweight SDK, developers gain immediate visibility into request activity, response behavior, 
                    failures, latency patterns, and endpoint usage without modifying existing business logic.
                  </p>
                  <p>
                    The goal is simple: Understand what your application is sending, how external services are 
                    responding, and where performance issues originate.
                  </p>
                  <p>
                    Whether you're debugging a production incident, validating a new integration, investigating 
                    latency spikes, or simply trying to understand how your application communicates with external 
                    systems, RequestVault provides the context you need.
                  </p>
                </div>
              </section>

              {/* Why RequestVault Exists */}
              <section id="why-requestvault" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Why RequestVault Exists</h2>
                <div className="space-y-6 text-vault-text-secondary">
                  <p>
                    Observability tooling has traditionally focused on servers, infrastructure, and internal 
                    application metrics. Outbound API traffic often receives far less attention despite being one 
                    of the most common sources of production issues.
                  </p>
                  <p>A single failing dependency can cause:</p>
                  <ul className="list-disc list-inside space-y-2 ml-2">
                    <li>Authentication failures</li>
                    <li>Payment processing errors</li>
                    <li>AI service disruptions</li>
                    <li>Increased latency</li>
                    <li>Cascading application failures</li>
                    <li>Poor customer experience</li>
                  </ul>
                  <p>
                    Most teams discover these problems only after users begin reporting them. RequestVault focuses 
                    specifically on the layer where applications communicate with external services. By capturing 
                    outbound HTTP traffic, RequestVault makes those interactions visible, searchable, and measurable.
                  </p>
                </div>
              </section>

              {/* Core Capabilities */}
              <section id="core-capabilities" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Core Capabilities</h2>
                <div className="space-y-8">
                  {/* Request Inspection */}
                  <div className="bg-vault-surface border border-vault-border rounded-xl p-6">
                    <h3 className="text-xl font-semibold text-vault-text mb-4">Request Inspection</h3>
                    <p className="text-vault-text-secondary mb-4">
                      Every captured request can be inspected in detail. Developers can view:
                    </p>
                    <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm text-vault-text-secondary list-disc list-inside">
                      <li>HTTP method</li>
                      <li>Endpoint URL</li>
                      <li>Status code</li>
                      <li>Response time</li>
                      <li>Request headers</li>
                      <li>Response headers</li>
                      <li>Request payload</li>
                      <li>Response payload</li>
                      <li>User-Agent information</li>
                      <li>Timestamp information</li>
                    </ul>
                    <p className="text-vault-text-secondary mt-4">
                      This makes it possible to reconstruct exactly what happened during an API interaction.
                    </p>
                  </div>

                  {/* Traffic Analytics */}
                  <div className="bg-vault-surface border border-vault-border rounded-xl p-6">
                    <h3 className="text-xl font-semibold text-vault-text mb-4">Traffic Analytics</h3>
                    <p className="text-vault-text-secondary mb-4">
                      Raw request data becomes significantly more valuable when aggregated. RequestVault continuously 
                      analyzes captured traffic and provides insights such as:
                    </p>
                    <ul className="space-y-2 text-sm text-vault-text-secondary list-disc list-inside">
                      <li>Request volume trends</li>
                      <li>Success and failure rates</li>
                      <li>Endpoint popularity</li>
                      <li>Response latency trends</li>
                      <li>Slowest endpoints</li>
                      <li>Error-prone integrations</li>
                      <li>Recent request activity</li>
                    </ul>
                  </div>

                  {/* Failure Visibility */}
                  <div className="bg-vault-surface border border-vault-border rounded-xl p-6">
                    <h3 className="text-xl font-semibold text-vault-text mb-4">Failure Visibility</h3>
                    <p className="text-vault-text-secondary">
                      Not all failures generate HTTP responses. Network interruptions, DNS failures, connection 
                      issues, and timeout exceptions frequently disappear into application logs. RequestVault 
                      captures these events alongside successful requests.
                    </p>
                    <div className="mt-4 bg-vault-bg border border-vault-border rounded-lg p-4">
                      <p className="text-sm text-vault-text-secondary mb-2">Failed requests are stored with:</p>
                      <pre className="text-vault-accent font-mono text-sm overflow-x-auto">{`{
  "status_code": 0
}`}</pre>
                    </div>
                  </div>
                </div>
              </section>

              {/* Getting Started */}
              <section id="getting-started" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Getting Started</h2>
                <div className="space-y-8 text-vault-text-secondary">
                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Create an Account</h3>
                    <p>
                      Create a RequestVault account and complete email verification. Once registration is complete, 
                      a dedicated workspace is created for your account.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Retrieve Your API Key</h3>
                    <p>
                      Each workspace receives a unique API key. This key identifies your application and authorizes 
                      telemetry submission to RequestVault. Keep this key private.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Install the SDK</h3>
                    <div className="bg-vault-surface border border-vault-border rounded-lg p-4">
                      <div className="flex items-center justify-between">
                        <code className="text-vault-accent font-mono">pip install requestvault</code>
                        <button
                          onClick={() => copyToClipboard('pip install requestvault', 'install')}
                          className="text-vault-text-secondary hover:text-vault-text transition-colors"
                        >
                          {copied === 'install' ? <Check size={16} /> : <Copy size={16} />}
                        </button>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Initialize RequestVault</h3>
                    <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                      <pre>{`from requestvault import RequestVault

RequestVault.init(
    api_key="YOUR_API_KEY"
)`}</pre>
                    </div>
                    <p className="mt-3 text-sm text-vault-text-secondary">
                      After initialization, RequestVault begins monitoring supported HTTP traffic automatically.
                    </p>
                  </div>
                </div>
              </section>

              {/* How It Works */}
              <section id="how-it-works" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">How It Works</h2>
                <div className="space-y-6 text-vault-text-secondary">
                  <p>
                    RequestVault integrates directly with the Python <code className="text-vault-accent">requests</code> ecosystem. 
                    Internally, the SDK instruments <code className="text-vault-accent">requests.Session.request</code>.
                  </p>
                  <p>
                    When a request is executed, the SDK:
                  </p>
                  <ol className="list-decimal list-inside space-y-2 ml-2">
                    <li>Captures request metadata</li>
                    <li>Measures request duration</li>
                    <li>Records response information</li>
                    <li>Queues telemetry data</li>
                    <li>Sends telemetry asynchronously in the background</li>
                  </ol>
                  <p>
                    Because transmission occurs through a separate worker process, application execution remains unaffected. 
                    Monitoring should never interfere with application behavior.
                  </p>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Automatic Data Collection</h3>
                    <div className="bg-vault-surface border border-vault-border rounded-xl p-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4 text-sm">
                        <div><span className="font-medium text-vault-text">Request Information:</span> Method, endpoint, headers, payload</div>
                        <div><span className="font-medium text-vault-text">Response Information:</span> Status code, headers, payload</div>
                        <div><span className="font-medium text-vault-text">Performance Metrics:</span> Response time</div>
                        <div><span className="font-medium text-vault-text">Environment Data:</span> User-Agent</div>
                        <div><span className="font-medium text-vault-text">Failure Information:</span> Timeouts, connection failures, DNS errors</div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <p className="text-sm mb-3">Example request that will automatically appear in your dashboard:</p>
                    <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                      <pre>{`import requests

response = requests.get(
    "https://api.github.com/users/octocat"
)`}</pre>
                    </div>
                  </div>
                </div>
              </section>

              {/* SDK Configuration */}
              <section id="sdk-configuration" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">SDK Configuration</h2>
                <div className="space-y-8">
                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">API Key (Required)</h3>
                    <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                      <pre>{`RequestVault.init(
    api_key="rv_xxxxxxxxxxxxxxxxx"
)`}</pre>
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">URL Inclusion Filtering</h3>
                    <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                      <pre>{`RequestVault.init(
    api_key="YOUR_API_KEY",
    include_urls=[
        "api.stripe.com",
        "api.github.com"
    ]
)`}</pre>
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">URL Exclusion Filtering</h3>
                    <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                      <pre>{`RequestVault.init(
    api_key="YOUR_API_KEY",
    exclude_urls=[
        "localhost",
        "127.0.0.1"
    ]
)`}</pre>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <h4 className="font-semibold text-vault-text mb-2">Header Collection</h4>
                      <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                        <pre>{`capture_headers=False`}</pre>
                      </div>
                    </div>
                    <div>
                      <h4 className="font-semibold text-vault-text mb-2">Request Body Collection</h4>
                      <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                        <pre>{`capture_request_body=False`}</pre>
                      </div>
                    </div>
                    <div>
                      <h4 className="font-semibold text-vault-text mb-2">Response Body Collection</h4>
                      <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                        <pre>{`capture_response_body=False`}</pre>
                      </div>
                    </div>
                    <div>
                      <h4 className="font-semibold text-vault-text mb-2">Maximum Payload Size</h4>
                      <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto">
                        <pre>{`max_body_size=10000`}</pre>
                      </div>
                    </div>
                  </div>
                </div>
              </section>

              {/* Dashboard Analytics */}
              <section id="dashboard-analytics" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Dashboard Analytics</h2>
                <div className="text-vault-text-secondary space-y-4">
                  <p>The RequestVault dashboard transforms raw request data into operational insights.</p>
                  <ul className="list-disc list-inside space-y-3 ml-2">
                    <li><span className="font-medium text-vault-text">Request Volume:</span> Visualize request activity over time</li>
                    <li><span className="font-medium text-vault-text">Response Time Trends:</span> Track average latency and identify performance degradation</li>
                    <li><span className="font-medium text-vault-text">Status Distribution:</span> Monitor 2xx, 3xx, 4xx, 5xx, and failed requests</li>
                    <li><span className="font-medium text-vault-text">Top Endpoints:</span> Identify the endpoints responsible for the majority of traffic</li>
                    <li><span className="font-medium text-vault-text">Slow Endpoints:</span> Surface integrations contributing the most latency</li>
                    <li><span className="font-medium text-vault-text">Recent Activity:</span> Review the latest captured requests as they occur</li>
                  </ul>
                </div>
              </section>

              {/* Security and Privacy */}
              <section id="security-and-privacy" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Security and Privacy</h2>
                <div className="space-y-6 text-vault-text-secondary">
                  <p>
                    RequestVault was designed with security as a foundational concern. Sensitive values are redacted 
                    before storage, including passwords, access tokens, refresh tokens, API keys, authorization headers, 
                    and cookies.
                  </p>
                  <p>
                    Large payloads are truncated to configurable limits. RequestVault also provides filtering controls 
                    that allow developers to exclude sensitive endpoints entirely.
                  </p>
                </div>
              </section>

              {/* Production Recommendations */}
              <section id="production-recommendations" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Production Recommendations</h2>
                <div className="bg-vault-surface border border-vault-border rounded-xl p-6">
                  <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto mb-6">
                    <pre>{`RequestVault.init(
    api_key="PRODUCTION_API_KEY",
    capture_headers=True,
    capture_request_body=False,
    capture_response_body=False,
    max_body_size=5000
)`}</pre>
                  </div>
                  <ul className="space-y-2 text-vault-text-secondary list-disc list-inside ml-2">
                    <li>Use dedicated  API key</li>
                    <li>Exclude internal health check endpoints</li>
                    <li>Limit payload collection where possible</li>
                    <li>Monitor only the traffic necessary for operational visibility</li>
                  </ul>
                </div>
              </section>

              {/* Troubleshooting */}
              <section id="troubleshooting" className="scroll-mt-20">
                <h2 className="text-3xl font-bold text-vault-text mb-6">Troubleshooting</h2>
                <div className="space-y-8">
                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Requests Are Not Appearing</h3>
                    <ul className="list-disc list-inside space-y-2 text-vault-text-secondary ml-2">
                      <li>Verify SDK initialization executed successfully</li>
                      <li>Verify API key is valid</li>
                      <li>Check network connectivity</li>
                      <li>Ensure URL filters are not excluding traffic</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Failed Requests Not Appearing</h3>
                    <p className="text-vault-text-secondary">
                      Ensure requests are executed through the <code className="text-vault-accent">requests</code> library and not through unsupported HTTP clients.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Missing Request Bodies</h3>
                    <p className="text-vault-text-secondary">
                      Verify that payload collection is enabled(they are true by default):
                    </p>
                    <div className="bg-vault-bg rounded-lg p-4 font-mono text-sm text-vault-accent overflow-x-auto mt-3">
                      <pre>{`capture_request_body=True
                        capture_response_body=True`}</pre>
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold text-vault-text mb-3">Delayed Updates</h3>
                    <p className="text-vault-text-secondary">
                      RequestVault uses asynchronous telemetry transmission. Minor delays are expected and are intentionally 
                      introduced to ensure application performance remains unaffected.
                    </p>
                  </div>
                </div>
              </section>

              {/* Support */}
              <section className="border-t border-vault-border pt-12">
                <h2 className="text-2xl font-bold text-vault-text mb-4">Need Help?</h2>
                <p className="text-vault-text-secondary mb-4">
                  If you have questions or need assistance, reach out to our support team:
                </p>
                <ul className="space-y-2 text-vault-accent">
                  <li>
                    <a href="mailto:varizzup@gmail.com" className="hover:text-vault-accent-hover transition-colors">
                      varizzup@gmail.com
                    </a>
                  </li>
                  <li>
                    <a href="https://github.com/VarunVashisth" className="hover:text-vault-accent-hover transition-colors">
                      GitHub 
                    </a>
                  </li>
                </ul>
              </section>
            </main>
          </div>
        </div>
      </div>
    </PublicLayout>
  )
}